name: Build SDL3 for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build SDL3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SDL3 Source
        uses: actions/checkout@v4
        with:
          repository: libsdl-org/SDL
          ref: release-3.2.8  # Change to desired version

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          local-cache: true

      - name: Configure and Build SDL3 (arm64-v8a)
        run: |
          mkdir -p build-android && cd build-android
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DBUILD_SHARED_LIBS=ON \
            -DSDL_STATIC=OFF \
            -DSDL_SHARED=ON \
            -DSDL3_BUILD_SHARED_LIBS=ON \
            -GNinja
          ninja
          find . -name "*.so" || echo "Shared library not found!"

      - name: Upload libSDL3.so
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: libSDL3-arm64-v8a
          path: build-android/src/libSDL3.so
